### PR TITLE
Fix compile errors on GWT 2.8.2

### PR DESCRIPTION
**Pull request by adrianmsmith**

### CODE REVIEW

**Comment by hohwille** [comment]
@adrianmsmith thanks for your contribution.
To be honest, I more or less gave up on GWT. If you want to maintain this project, I am happy to hand it over to you. IMHO still the best place would be to bring this directly into the GWT project itself. However, as you already figured out JSR310 is complicated and to bring all features to the client would be a huge pile of work...

**Comment by adrianmsmith** [comment]
Hey, yes I would be happy to take over maintainership of this project. Do you know how one does that? Is there a GitHub feature for that, or we just announce in the README that I am maintaining my repository now?

Could I ask, where did the code code from? Did you write it, or did it come from somewhere else? Are we sure that there are no copyright issues in the code? (That someone comes along at a later date and claims they wrote the code and that it's e.g. commercial)

I think I would not do much more than you - I am using this library in a new project, so if I find bugs or features I need then I'll add them. And I'm happy to review and accept pull requests from anyone. But I probably won't do much more than that. But I figure that's better than nothing.

**Comment by hohwille** [comment]
There are several options:
* I can simply transfer this repository to you (a github organization owned by you or directily to your user `adrianmsmith`).
* I grant you admin permissions for this repo
* You create a fork of this repo and keep working and maintaining on that fork
* You create a new fresh repo whereever you like and copy the code over to it.

(UPDATE: officially I can only speak about copyright of my code and not work taken from others as clarified below)
I am happy with whatever suits you best. Also I do not care much about the copyright of my code. You may refactor it to a new package namespace, change maven groupId and artifactId, etc. as you like. I can also send you a PGP signed Email confirming that again. My only requirements would be obvious: code should remain open-source and you shall not reject my authorship.
Have fun with it.

**Comment by adrianmsmith** [comment]
Before I take it over - Regarding copyright, I was just wondering where the code came from? It doesn't seem to have been originally designed for GWT, so I was wondering if it came from another project? I see that most of the source files have "Copyright (c) 2007-2012, Stephen Colebourne & Michael Nascimento Santos" at the top. I think this source code was derived from https://www.threeten.org/ which seems to have been released under a BSD (not Apache) license (as far as I can tell?) Honestly I'm no expert on this sort of stuff, I was just wondering if you had more information there, and was sure that everything was OK in terms of copyright of the code that already exists.

**Comment by hohwille** [comment]
Ups. Too long ago, ideed. Thanks for taking this serious.
Your observation is perfectly right. I researched my emails and found a correspondence on this I made with Stephen Colebourne:
```
Hi Jorg,
I have no problems with the threetenbp code being used in this way,
especially from a legal POV - the BSD license was intended for this
kind of use case.

Bear in mind that the code forked from the actual JDK 8 codebase a
while back, and as such there may be subtle differences. In
particular, some interfaces have been converted to abstract classes,
and method references have been converted to constants. The Hijrah
calendar system is completely incompatible and you should not rely on
it as is.

The code in git now is the code to use, not the last released code (in
maven central). The current code passes most of the test cases from
JDK 8, though not every last one. It is almost ready for another
release.

Feel free to send me pull requests for areas where you find
differences with JDK 8, such as the Hijrah calendar system.

thanks, and feel free to ask more questions,
Stephen



On 7 April 2014 21:50, Jörg Hohwiller wrote:
> Hi Stephen,
>
> for Google Web Toolkit we are looking forward to supporting JSR310
> (java.time).
> Therefore we would like to include source code derived from your javax.time
> backport:
> https://github.com/ThreeTen/threetenbp
> with some modifications (package change to java.time, changes for GWT
> compatibility, etc.).
>
> I am already aware of your statement about the namespace:
>
>> JDK8 is using the java.time namespace, not javax.time. As such, there
>> is no way to create a compatible backport without using the bootstrap
>> classpath. Such a backport would also violate the JCP/JSR rules as
>> only compatible implementations can use the namespace.
>
>
> But for GWT we are not providing a backport for Java < 1.8 nor compiled code
> at all but just
> GWT compatible source-code (located in some com/google/emul/java/time
> location) so GWT
> compiler can transform Java 1.8 code using java.time to JavaScript that runs
> in the browser (with some obvious limitations).
>
> Are there any concerns or legal issues we might be missing?
> http://www.gwtproject.org/makinggwtbetter.html#clas
>
> All files will carry some "Copyright YYYY Google Inc." header together with
> a ASL 2.0 License note.
> I do not want to do this without some sort of (informal) confirmation or
> permission.
> Of course we would keep the original author credit in JavaDocs, etc.
> Feel free to forward to other contributors of the ThreeTen project.
>
> Hope to hear from you.
> Thanks
>   Jörg
```

If you want to have the original mail, please send me an email to hohwille at users.sourceforge.net (see my git commits) so I can forward it to you.
Also I give you permission to change the license from ASL 2.0 to BSD if that helps you in any way.

**Comment by adrianmsmith** [comment]
Ah that all sounds great, thanks for confirming this!

So yeah, I am happy to take over ownership of this project. I think the best approach would be if you transfer it to my account (adrianmsmith)

I have deleted my fork (as the instructions on GitHub state that you can't transfer a repository to someone with a fork.)

**Pull request merged**
